### ISSUE TITLE
contact with you

### ISSUE THREAD

**Issue by eugene-pascal** [AnthonyW2/4DChess#1]
Dear Anthony, a colleague of mine would like to write you a message concerning 4D chess, would you give me your email address or any other way of contacting you?

**Comment by AnthonyW2** [comment]
Hello Yevgenii, I am interested in hearing from this colleague of yours.
There is a Discord server created by Shaun Wu, the owner of the [Chess in 5D](https://gitlab.com/5d-chess/chess-in-5d) project (another open-source version of the game [5D Chess with Multiverse Time Travel](https://www.5dchesswithmultiversetimetravel.com/)): https://discord.com/invite/Df44sHt. You can contact me and other users who have worked on similar projects through that Discord server.
Keep in mind that my project is presently inactive. While I would like to continue working on it and enhancing it, I am currently working on other things.

If Discord is not a viable contact option for you/your colleague, I can send my email address, though Discord is currently my preferred option for this project.
